name: Test code, build docker image and push it

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12.4"
          
      - name: Install dependencies
        run: |
          cd docker
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Check PEP8 compliance
        run: |
          black --check -v .
          
      - name: Lint with pyflakes
        run: |
          pyflakes .
          
      - name: Unit tests with pytest
        run: echo "Here we need to run unit tests"
        
      - name: Integration tests with pytest
        run: echo "Here we need to run integration tests"


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6.6.1
        with:
          context: docker/
          file: docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/antifraud:latest
